[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  # Optional: Add environment variables here
  # Example: REACT_APP_API_URL = "https://example.com/api"

[functions]
  # Optional: Specify functions directory
  # directory = "netlify/functions"
